### ISSUE TITLE
Transfer ownership of this gem to Pedro Carrico

### ISSUE THREAD

**Issue by remen** [remen/fork_break#8]
Moved discussion here from #7

**Comment by remen** [comment]
Moved discussion here from https://github.com/remen/fork_break/pull/7

**Comment by remen** [comment]
@pedrocarrico Ok, was a bit fast creating this issue. I'll close it. Let me know if there is anything you need, and I'll try to help. Otherwise, best of luck and have fun!

**Comment by pedrocarrico** [comment]
@remen Thanks :+1:
